name: drupal-with-postgres

services:
  drupal:
    image: drupal:9
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
  
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - /var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge